[package]
name = "wasm-check"
version = "0.1.0"
edition = "2021"
description = "Check WebAssembly browser support"
repository = "https://github.com/jrmsdev/wasm-check"
license = "bsd"

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
